.TH CURSIVE 6 "24 July 1985"
.UC
.SH NAME
cursive \- print text in cursive script
.SH SYNOPSIS
.B /usr/games/cursive
[
.BI \-i n
]
[
.BI \-t n
]
[message]
.SH DESCRIPTION
.I Cursive
prints a line of text in a rather crude cursive script.
It is intended for use mainly for the generation of decorative signatures
for electronic mail.
If message text is given on the command line, that text is used.
Otherwise the text will be read from standard input up to an end of file.
The
.B \-i
option sets the minimum spacing between adjacent characters.
The default is
.B \-i1 .
The
.B \-t
option sets the length of the trailing lines on the end of each word.
The default is
.B \-t1 .
.PP
The '_' character is treated in a special way.  It may be inserted in
the text anywhere you wish to lengthen a connecting line between two
letters.
.SH BUGS
Many ASCII characters are not defined, notably the numbers and symbols.
Punctuation is mostly available.
Some characters are rather ugly.
The author has lousy handwriting.
.SH AUTHOR
Jan Wolter.  UUCP mail to janc@crim.eecs.umich.edu
.SH COPYRIGHT
This program and the cursive font it generates are copyrighted by Jan Wolter.
Both may be freely used and distributed in any way whatsoever, so long as
the author's name is left in the source code and documentation.
